name: Build Engines for Linux
on:
  workflow_dispatch:
    inputs:
      commit:
        description: "Commit on the given branch to build"
        required: true

jobs:
  build:
    # Do not change `name`, prisma-engines Buildkite build job depends on this name ending with the commit
    name: "Linux engines build on branch ${{ github.event.ref }} for commit ${{ github.event.inputs.commit }}"
    env:
      SQLITE_MAX_VARIABLE_NUMBER: 250000
      SQLITE_MAX_EXPR_DEPTH: 10000
    runs-on: ubuntu-latest

    steps:
      - name: Output link to real commit
        run: echo ${{ github.repository }}/commit/${{ github.event.inputs.commit }}

      - name: Checkout ${{ github.event.inputs.commit }}
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.commit }}

      - uses: actions-rust-lang/setup-rust-toolchain@v1

      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - run: cargo build --release -p schema-engine-cli

      - name: Upload binaries to latest
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ github.workspace }}/target/release/schema-engine
          asset_name: schema-engine-linux
          tag: latest
          overwrite: true
          body: "infdev"
